
package classRegister;

import java.awt.Toolkit;
import java.sql.DriverManager;
import java.sql.SQLException;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.Statement;
import javax.swing.JOptionPane;

/**
 *
 * @author GIPRIM
 */
public class UpdateStudent extends javax.swing.JFrame {
    
    final String DATABASE_URL = "jdbc:sqlserver://localhost:1433;" + "databaseName=GITECK;integratedSecurity=true";
    Connection connect;
    Statement prep;
    ResultSet rs;
    
    String stringOne;
    String stringTwo;
    //String programText;
    
    int studentId;
    int idFromProgram;
    
    /** Creates new form UpdateStudent */
    public UpdateStudent() {
        initComponents();
        updateCombo();
        favicon();
    }
    
    
    private void favicon(){
        setIconImage(Toolkit.getDefaultToolkit().getImage(getClass().getResource("collegeLcolor.png")));
    }
    
    
     //Update comboBox
    private void updateCombo(){
        final String sql = "SELECT * FROM STUDENT";
   
        try{
            connect = DriverManager.getConnection(DATABASE_URL);
            prep = connect.createStatement();
            rs = prep.executeQuery(sql);
            
            while(rs.next()){
                studentList.addItem(rs.getString("FIRSTNAME") + " " + rs.getString("LASTNAME"));
            }
                     
        }catch(SQLException e){
            e.printStackTrace();
        }
        finally{
            try{
                prep.close();
                rs.close();
                connect.close();
            }catch(SQLException e){
                e.printStackTrace();
            }
        }
    }
    
    // GETTING THE PROGRAMID IN FROM THE DATABASE
     void getProgramId(){
        final String sql = "SELECT * FROM PROGRAMS WHERE PROGRAM=?";
       
       try(
               Connection connection = DriverManager.getConnection(DATABASE_URL);
               PreparedStatement preparedStatement = connection.prepareStatement(sql);
            ){
            String programText = (String)programsList.getSelectedItem();
            
            preparedStatement.setString(1,programText.toUpperCase());
            
            ResultSet resul = preparedStatement.executeQuery();
            
           
             if(resul.next())
                  idFromProgram = resul.getInt("PROGRAMID");
                 
            
                     
        }catch(SQLException e){
            e.printStackTrace();
        }
     
      
    }
     
     
    //FETCHING THE TEXT IN THE COMBO BOX
     void getComboxText(){
        String textOne = (String)studentList.getSelectedItem();
        
        if(!textOne.equals("Select Student")){
        String[] textTwo = textOne.split(" ");
        
        stringOne = textTwo[0].toString();
        stringTwo = textTwo[1].toString();
        }
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        fNameFld = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        lNameFld = new javax.swing.JTextField();
        programsList = new javax.swing.JComboBox<>();
        jLabel4 = new javax.swing.JLabel();
        genderList = new javax.swing.JComboBox<>();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        studentList = new javax.swing.JComboBox<>();
        jLabel7 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Students > Update");
        setBackground(new java.awt.Color(255, 255, 255));
        setLocation(new java.awt.Point(500, 290));
        setResizable(false);

        jLabel2.setBackground(new java.awt.Color(255, 255, 255));
        jLabel2.setForeground(new java.awt.Color(0, 153, 153));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/classRegister/userM.png"))); // NOI18N

        jLabel3.setBackground(new java.awt.Color(255, 255, 255));
        jLabel3.setFont(new java.awt.Font("Comic Sans MS", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 153, 153));
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel3.setText("First Name:");

        fNameFld.setFont(new java.awt.Font("Comic Sans MS", 1, 14)); // NOI18N
        fNameFld.setForeground(new java.awt.Color(0, 153, 153));

        jLabel1.setBackground(new java.awt.Color(255, 255, 255));
        jLabel1.setFont(new java.awt.Font("Comic Sans MS", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 153, 153));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Edit Student's Info");

        jButton2.setBackground(new java.awt.Color(255, 255, 255));
        jButton2.setFont(new java.awt.Font("Comic Sans MS", 1, 14)); // NOI18N
        jButton2.setForeground(new java.awt.Color(0, 153, 153));
        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/classRegister/update.png"))); // NOI18N
        jButton2.setText("Update");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        lNameFld.setFont(new java.awt.Font("Comic Sans MS", 1, 14)); // NOI18N
        lNameFld.setForeground(new java.awt.Color(0, 153, 153));

        programsList.setEditable(true);
        programsList.setFont(new java.awt.Font("Comic Sans MS", 0, 14)); // NOI18N
        programsList.setForeground(new java.awt.Color(0, 153, 153));

        jLabel4.setBackground(new java.awt.Color(255, 255, 255));
        jLabel4.setFont(new java.awt.Font("Comic Sans MS", 1, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 153, 153));
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel4.setText("Last Name:");

        genderList.setEditable(true);
        genderList.setFont(new java.awt.Font("Comic Sans MS", 0, 14)); // NOI18N
        genderList.setForeground(new java.awt.Color(0, 153, 153));

        jLabel5.setBackground(new java.awt.Color(255, 255, 255));
        jLabel5.setFont(new java.awt.Font("Comic Sans MS", 1, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(0, 153, 153));
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel5.setText("Program:");

        jLabel6.setBackground(new java.awt.Color(255, 255, 255));
        jLabel6.setFont(new java.awt.Font("Comic Sans MS", 1, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(0, 153, 153));
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel6.setText("Gender:");

        studentList.setFont(new java.awt.Font("Comic Sans MS", 0, 14)); // NOI18N
        studentList.setForeground(new java.awt.Color(0, 153, 153));
        studentList.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select Student" }));
        studentList.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                studentListActionPerformed(evt);
            }
        });

        jLabel7.setBackground(new java.awt.Color(255, 255, 255));
        jLabel7.setFont(new java.awt.Font("Comic Sans MS", 1, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(0, 153, 153));
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel7.setText("Select the student you want to edit their info");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 787, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addGap(52, 52, 52)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(genderList, 0, 230, Short.MAX_VALUE)
                                    .addComponent(fNameFld))
                                .addGap(111, 111, 111)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(programsList, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(lNameFld, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 787, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(67, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 582, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(studentList, javax.swing.GroupLayout.PREFERRED_SIZE, 582, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(138, 138, 138))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(376, 376, 376))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(25, 25, 25)
                        .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(studentList, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(48, 48, 48)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(fNameFld, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lNameFld, javax.swing.GroupLayout.DEFAULT_SIZE, 36, Short.MAX_VALUE)
                            .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(genderList)
                            .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(programsList)))
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(49, 49, 49)
                .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(42, 42, 42))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void studentListActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_studentListActionPerformed
        
     
        getComboxText();
        insertUpdate();
        getProgramId();
        
          
    }//GEN-LAST:event_studentListActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        if(
            !fNameFld.getText().equals("") &&
            !lNameFld.getText().equals("")             
          ){
            final String UPDATE_STATEMENT = "UPDATE STUDENT SET FIRSTNAME=?, LASTNAME=?, GENDER=?, PROGRAMID=? WHERE STUDENTID=?";
            
            try(
               Connection connection = DriverManager.getConnection(DATABASE_URL);
               PreparedStatement preparedStatement = connection.prepareStatement(UPDATE_STATEMENT);
               ){
                
                String genderText = (String)genderList.getSelectedItem();
                
                
                
                preparedStatement.setString(1, fNameFld.getText().toUpperCase());
                preparedStatement.setString(2, lNameFld.getText().toUpperCase());
                preparedStatement.setString(3, genderText.toUpperCase());
                preparedStatement.setInt(4, idFromProgram);
                preparedStatement.setInt(5, studentId);
                
                
                preparedStatement.executeUpdate();
                
                JOptionPane.showMessageDialog(this,"Student Update","Edit Form", JOptionPane.INFORMATION_MESSAGE);
            }
            catch(SQLException e){
                JOptionPane.showMessageDialog(this,"DATABASE ERROR","Edit Form", JOptionPane.ERROR_MESSAGE);
                e.printStackTrace();
            }
        }
        
                fNameFld.setText("");
                lNameFld.setText("");
                genderList.setSelectedItem("");
                programsList.setSelectedItem("");
    }//GEN-LAST:event_jButton2ActionPerformed

    private void insertUpdate(){
        
        
        if(!studentList.equals("Select Student")){
            final String SELECT_QUERY = 
            "SELECT STUDENTID, FIRSTNAME,LASTNAME,GENDER,PROGRAM FROM STUDENT JOIN PROGRAMS ON STUDENT.PROGRAMID=PROGRAMS.PROGRAMID WHERE FIRSTNAME=? AND LASTNAME=?";
            
            ResultSet resultSet;
            try(
                    Connection connection = DriverManager.getConnection(DATABASE_URL);
                    PreparedStatement preparedStatement = connection.prepareStatement(SELECT_QUERY);
               ){
                
                
                // used to insert the missing values for the sql (?) 
                //the setString method takes 2 arguments an int and the value with a matching dataType
                
                preparedStatement.setString(1,stringOne);
                preparedStatement.setString(2,stringTwo);
                
                // with this line of code we run the query
                resultSet = preparedStatement.executeQuery();
                
                if(resultSet.next()){
                   studentId = resultSet.getInt("STUDENTID");
                    
                    //here we write a code that will fill up the provided textFields in the GUI with the 
                    // right SQL data
                    fNameFld.setText(resultSet.getString("FIRSTNAME"));
                    lNameFld.setText(resultSet.getString("LASTNAME"));
                    programsList.addItem(resultSet.getString("PROGRAM"));
                    genderList.addItem(resultSet.getString("GENDER"));
          
                    
                    // HERE WE DISPLAY A POPUP BOX GIVING US UPDATE IF THE SEARCHED FIRSTNAME AND LASTNAME WAS FOUND
                    //JOptionPane.showMessageDialog(this, "Author Found", "Edit form", JOptionPane.INFORMATION_MESSAGE);
                }
                
                
                
            }catch(SQLException e){
                //here, if there seems to be any error, this will come up
                JOptionPane.showMessageDialog(this, "Database Error", "Edit form", JOptionPane.ERROR_MESSAGE);
            }
            
           
        }
        
        
    }
    
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(UpdateStudent.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(UpdateStudent.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(UpdateStudent.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(UpdateStudent.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new UpdateStudent().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField fNameFld;
    private javax.swing.JComboBox<String> genderList;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JTextField lNameFld;
    private javax.swing.JComboBox<String> programsList;
    private javax.swing.JComboBox<String> studentList;
    // End of variables declaration//GEN-END:variables

}
